### ISSUE TITLE
Show warnings for Allergens

### ISSUE THREAD

**Issue by aleene** [aleene/FoodViewer#100]
Allow the user to set triggers on allergens. If the product contains an allergen, the user is warned, through a visual (audio?) warning. The background of the product could turn red for instance.

**Comment by teolemon** [comment]
List of allergens
http://world.openfoodfacts.org/allergens.json
http://world.openfoodfacts.org/allergens.xml
[edit]Individual allergen
http://world.openfoodfacts.org/allergen/fish.json
http://world.openfoodfacts.org/allergen/fish.xml

**Comment by aleene** [comment]
In the preferences panel allow the user to set one or more warning allergens. Create a table row which opens a secondary controller.Use the translated allergen list for this. This will set a boolean in the allergen table. 
If a warning is triggered, change the colour background of the product to red. And set the colour of the trigger allergen tag to red as well.

**Comment by aleene** [comment]
After setting an allergen warning, I should reload the master table.

**Comment by aleene** [comment]
Seems to work
