### ISSUE TITLE
Show original emb-codes

### ISSUE THREAD

**Issue by aleene** [aleene/FoodViewer#118]
The current packager codes has been "normalized" by OFF. Should be simply a change in json key.

**Comment by teolemon** [comment]
Packager codes
[edit]List of Packager codes
http://world.openfoodfacts.org/packager-codes.json
http://world.openfoodfacts.org/packager-codes.xml
[edit]List of products with given Packager code
http://world.openfoodfacts.org/packager-code/emb-35069c.json
http://world.openfoodfacts.org/packager-code/emb-35069c.xml

**Comment by aleene** [comment]
Required to adapt the regex decoders AND the json entry is a string and not an array of string.
