### ISSUE TITLE
Add ability to edit data

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#121]
The user should be able to change existing products, i.e. editing existing values and also add to existing values.

**Comment by aleene** [comment]
Ideally I would be able to switch between edit- and view-mode. Switching to view-mode should save any changes. Switching to edit-mode should change the labels to textFields or even textViews. Maybe I can replace the UILabels with UITextFields. Inview-mode these UITextfields should be non-editable and the field-markers should not be there.

**Comment by aleene** [comment]
I added a button to switch into edit-mode. The UILabels can be changed to UITextFields. Ty delgate method sets the textfield into edit mode. I needed to pass a change of editmode in th pageviewcontroller onto the pages.

**Comment by aleene** [comment]
How to do saving the changes? And when?
- I can create a copy of the product, with just the barcode and all the other fields set to nil. Any change is added to this product. Thus I can change the product by just uploading the fields, which are no longer nil.

**Comment by aleene** [comment]
Editing for all field is implemented. Obvious bugs have been found.

Started alpha-testing (i.e. using it on my iPad to work with OFF).
