### ISSUE TITLE
Add padding on top of the Settings and Alert Settings views.

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#152]
Add padding on top of the Settings and Alert Settings views.
Currently the buttons are overlapping with the top status bar.

**Comment by aleene** [comment]
This is true for all screens

**Comment by aleene** [comment]
Either I hide the status bar or I put the content below. I think I prefer to have it below.

**Comment by aleene** [comment]
Not easy to find, but I think I have nailed it:
* In the Storyboard make sure the Presentation of the VC is set to Full Screen, Under Bottom Bars checked (the other Extend Edges unchecked);
* In the presented VC code add:
`    override func prefersStatusBarHidden() -> Bool {
        return true
    }
`
