### ISSUE TITLE
Make everything "clickable"

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#157]
Adding the ability to tap on a Brand/Category/Tag and be able to browse related products, just like on the website.

**Comment by aleene** [comment]
Seems for version 3

**Comment by aleene** [comment]
I could as a start open Safari with the tag encoded in the url

**Comment by aleene** [comment]
Basically this seems like search queries. I could present the results of such a query similar to the current history.

**Comment by aleene** [comment]
Added a tab for the search result. Tapping on a tag should then start a search, and will be shown in the search result tab.

**Comment by teolemon** [comment]
👍

**Comment by aleene** [comment]
Added a UITabViewController to the products pane. The user can then switch between his recents and the latest search query.
First step is to get the search query working within the structure of the app.

**Comment by aleene** [comment]
Set it up in such a way that selecting any tag can initiate a search.
Test first with a brand and a packaging tag.

**Comment by aleene** [comment]
All tags are now clickable.
Now need to finetune the app flow (editing search results is not possible), (show that the app is waiting for results), (products title not always correct)....

**Comment by aleene** [comment]
Title seems to work now, as is changing tabs.

**Comment by aleene** [comment]
You can now load the next set of a query.

**Comment by aleene** [comment]
Will close this as most is finished. Remaining items can become separate issues.
