### ISSUE TITLE
Support multilingual images

### ISSUE THREAD

**Issue by aleene** [aleene/FoodViewer#168]
For each language there can be corresponding image file. How must this be supported?

**Comment by aleene** [comment]
The current problem is that the url's to these other images are not available at the moment. They seem to be available in language-specific json files. I do not want to read multiple jsons just to step through the languages.

**Comment by teolemon** [comment]
For reference:
https://github.com/openfoodfacts/openfoodfacts-server/issues/460

**Comment by aleene** [comment]
Example json:
selected_images":{"nutrition":{"thumb":{"en":"https://static.openfoodfacts.org/images/products/073/762/806/4502/nutrition_en.12.100.jpg"},"display":{"en":"https://static.openfoodfacts.org/images/products/073/762/806/4502/nutrition_en.12.400.jpg"},"small":{"en":"https://static.openfoodfacts.org/images/products/073/762/806/4502/nutrition_en.12.200.jpg"}},"front":{"small":{"en":"https://static.openfoodfacts.org/images/products/073/762/806/4502/front_en.6.200.jpg"},"thumb":{"en":"https://static.openfoodfacts.org/images/products/073/762/806/4502/front_en.6.100.jpg"},"display":{"en":"https://static.openfoodfacts.org/images/products/073/762/806/4502/front_en.6.400.jpg"}},"ingredients":{"thumb":{"en":"https://static.openfoodfacts.org/images/products/073/762/806/4502/ingredients_en.10.100.jpg"},"display":{"en":"https://static.openfoodfacts.org/images/products/073/762/806/4502/ingredients_en.10.400.jpg"},"small":{"en":"https://static.openfoodfacts.org/images/products/073/762/806/4502/ingredients_en.10.200.jpg"}}},

**Comment by aleene** [comment]
Finished the part that reads the jsons. Not sure yet how I should store all the urls. I can use only the multilingual part. The older json keys for images are deprecated.
I only retrieve the urls, when the images are needed. This happens in another thread. Success is a notification, which can repaint the tableview.

I would like to match the retrieved image with the image that should be displayed, otherwise it might result in to many reloads.

**Comment by aleene** [comment]
Works for front images
