### ISSUE TITLE
Add images

### ISSUE THREAD

**Issue by aleene** [aleene/FoodViewer#226]
The user should be able to upload images related to a specific product. How could this look like?
- use the film roll for uploading. This might be the first step. If a user edits a specifc product, hebcan upload associated photos from the film roll;
- let the user use the camera as second option. Take a photo and then check if the user wants to upload the photo;
- associate photos. Let the user associate a photo with a specific item (main, ingredients, nut value).
- editing. Either let the user do it outside foodViewer, or add editing capibilities.
- support OFF editing stuff.

**Comment by teolemon** [comment]
Including a sentence: "Please only use photos you took yourself."

**Comment by aleene** [comment]
It seems that I can only upload photos associated with front/nutrients/ingredients.
The photos related to a product on OFF seem not accessible.

**Comment by aleene** [comment]
The user needs to do the following steps to add an image:
- set product in edit mode;
- push the add button in the image cell of the front/nutrients/ingredients page;
- select camera or photo library (or OFF library);
- take/select photo
- edit photo (crop only?)
- accept/done
- save

**Comment by aleene** [comment]
Image capture and saving is working. Now the upload.

**Comment by aleene** [comment]
Is working for front, ingredients and nutrition. And for multiple languages.
