### ISSUE TITLE
Gamification

### ISSUE THREAD

**Issue by aleene** [aleene/FoodViewer#227]
Can I add some gamification to the app?
- stats (number of products as contributor, creator, informer, photographer);
- activity timeline
- ranking timeline
Can the search interface help me with this?

**Comment by teolemon** [comment]
- We added the list of your products in the Android app (as a Webview, to reduce the amount of work)
- Missions needs changes server side (making it multilingual, plus an API)
- We created a point system for Open Food Hunt. Don't think there was an API for this.
- You could use the Game Center iOS thing to enable iOS specific ranking (Google Play Games also has an iOS api)
