### ISSUE TITLE
Prune translations

### ISSUE THREAD

**Issue by aleene** [aleene/FoodViewer#272]
Remove the translations in the code that are also in the storyboard.

**Comment by aleene** [comment]
Made a start by changing the texts in storyboard.

Next remove the localizations in code.

**Comment by teolemon** [comment]
I can help with getting the app translated in many languages if you provide me a translation file

**Comment by aleene** [comment]
Issue is that not only the app needs to be translated, but also the incorporated taxonomies need to be updated (extended for other languages). This makes the app rather big. I really need another solution to tap into the taxonomies.

**Comment by teolemon** [comment]
The taxonomies are in multilingual JSONs, as you probably already know.

**Comment by aleene** [comment]
There are no more translatable strings in the storyboard
