### ISSUE TITLE
Replace the <Products menu by a hamburger

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#350]
![image](https://cloud.githubusercontent.com/assets/1689815/22646444/be916306-ec6c-11e6-8e39-100767ea7c37.png)

**Comment by aleene** [comment]
I do not like hamburgers. It is non-standard. You are supposed to use a UINavigation controller as used by other IOS-apps.

**Comment by aleene** [comment]
This sums it up nicely: https://lmjabreu.com/post/why-and-how-to-avoid-hamburger-menus/
