### ISSUE TITLE
Remove . and ; in the Sidebar

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#397]
![image](https://cloud.githubusercontent.com/assets/1689815/24071715/ff826ea6-0bd8-11e7-9ef6-482776517e9d.png)

**Comment by aleene** [comment]
Can do. I am not yet happy with the supply chain summary though. Not sure what to put there ("Sold in 5 countries by 6 shops")?

**Comment by aleene** [comment]
Mostly implemented. Except the supply chain, which is a to complex sentence.
