### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#400]
## Before
![image](https://cloud.githubusercontent.com/assets/1689815/24071828/871f90bc-0bdb-11e7-8dd1-1c8a2618cbfe.png)

## After
![image](https://cloud.githubusercontent.com/assets/1689815/24071860/45908588-0bdc-11e7-9a1b-7178645121c3.png)

**Comment by aleene** [comment]
Can do, is there any template for that?

**Comment by teolemon** [comment]
Nope, it's a mockup.

**Comment by aleene** [comment]
Have to figure out some specific drawing code for this.

**Comment by aleene** [comment]
I liketo redesign the sidebar with more visual elements and less text.
I can use a linear gauge for the completeness. (https://github.com/ChiefPilot/F3BarGauge)
