### ISSUE TITLE
Nutrient tabs

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#401]
![image](https://cloud.githubusercontent.com/assets/1689815/24071894/0a21d2bc-0bdd-11e7-933f-e78f310a2dce.png)

Perhaps something based on additions

![image](https://cloud.githubusercontent.com/assets/1689815/24071982/afa5d8cc-0bde-11e7-86e6-7d6511df5b2c.png)

**Comment by aleene** [comment]
The purpose of the page is to give more insight into the calculation. I was looking for a visual approach, without the need to read the numbers. Numbers were supposed to be a second layer.

By the way double tapping gives you the french calculation.

**Comment by aleene** [comment]
The UI-interface element to convey a level is a slider:
https://developer.apple.com/ios/human-interface-guidelines/ui-controls/sliders/
I might experiment with this.

**Comment by aleene** [comment]
Using linear gauges here, might be nicer (https://github.com/ChiefPilot/F3BarGauge).
It should be visual and give insight how the calculatiin works.

**Comment by aleene** [comment]
Changed colours to horizontal gauges

**Comment by aleene** [comment]
Replaced the switches with images.

**Comment by aleene** [comment]
Seems finished.
