### ISSUE TITLE
Redesign Completeness

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#402]
![image](https://cloud.githubusercontent.com/assets/1689815/24072207/af8f34be-0be3-11e7-97c2-ce17b602bc71.png)
![image](https://cloud.githubusercontent.com/assets/1689815/24072212/bb1739da-0be3-11e7-8ee4-89e7cd5d9f80.png)

**Comment by aleene** [comment]
No, it must be visual. Text is to hard to decode.

In fact I use the page very often to check if something is missing. First I implemented it only to convey what was in the jsons. But it turned out to be useful.

**Comment by aleene** [comment]
For reference:
https://developer.apple.com/ios/human-interface-guidelines/ui-controls/switches/

**Comment by aleene** [comment]
http://www.infragistics.com/community/blogs/torrey-betts/archive/2013/10/15/using-cashapelayer-to-create-a-simple-indicator-objective-c.aspx

**Comment by aleene** [comment]
From apple:

> Be aware of colorblindness and how different cultures perceive color. People see colors differently. Many colorblind people, for example, find it difficult to distinguish red from green (and either color from gray), or blue from orange. Avoid using these color combinations as the only way to distinguish between two states or values. For example, instead of using red and green circles to indicate offline and online, use a red square and a green circle. Some image-editing software includes tools that can help you proof for colorblindness. Also consider how your use of color might be perceived in other countries and cultures. In some cultures, for example, red is used to communicate danger. In others, red has positive connotations. Make sure the colors in your app send the appropriate message.

**Comment by aleene** [comment]
So I will use to filled icons: a red square and a green circle.

**Comment by aleene** [comment]
Works
