### ISSUE TITLE
Create simple Open Beauty Facts switch in settings

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#406]
Adding a simple Open Beauty Facts setting in Food Viewer that would just change the API base URL

 ```https://ssl-api.openfoodfacts.org ``` >>  ```https://ssl-api.openbeautyfacts.org```

**Comment by aleene** [comment]
Implemented. Now trying to suppress the nutrition stuff.

**Comment by aleene** [comment]
Suppressed all the food specific stuff.
