### ISSUE TITLE
Combine the Scan icon and the Enter barcode field in the sidebar scanning tabbar

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#743]
Combine the Scan icon and the Enter barcode field in the sidebar into one field where you can either type a barcode or click on the icon to scan.
"Scan or enter a barcode"

**Comment by aleene** [comment]
The barcode field is not always visible, it can scroll away (is a feature of the software I used). I could add the barcode field to the page which does the scanning. But I use a standard component for scanning, so I have to hack my own.

**Comment by aleene** [comment]
I think I will move both to a contnous scanning tab.

**Comment by aleene** [comment]
Continued in #771.

**Comment by aleene** [comment]
Now #773.
