### ISSUE TITLE
Extend tab bar

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#744]
https://developer.apple.com/design/human-interface-guidelines/ios/bars/tab-bars/

This could incorporate:

Welcome screen:
- Scan
- History
- Settings

Product screen:
- Edit button
- Share button
- Settings

Search would be on the top right
https://developer.apple.com/design/human-interface-guidelines/ios/bars/navigation-bars/

The page system would go up at the top of a product (and be replaced by tabs)

**Comment by aleene** [comment]
That is not how you should use a tab bar. Tabs are not buttons! It is really to have different fairly unrelated parts of the app (see the Time app).  I have a tab bar on the first screen for products and search (I intend to a third one). On the product pages, I could add a button bar at the bottom (if I run out of space at the top). The page system puts the dots at the bottom (comes out of the box like that) and is not something I want to hack.

**Comment by aleene** [comment]
The tab-bar is for sections of the app. I have now a tab for **recents** (history) and **search**. I think I will add **scan** and **user**. Scan is what I have now and should evolve to continous scan. User is everything related to the user. I will add the preferences there as well.

**Comment by aleene** [comment]
#771 for the scanning tab.

**Comment by aleene** [comment]
Tabs now implemented.
