### ISSUE TITLE
Add a home screen

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#747]
Add a home screen

Idea 1: with the logo and mission statement of Open Food Facts, and a scan button (in a bottom bar with history, scan, search)
Idea 2: with the full screen history and a scan button (in a bottom bar with history, scan, search)

**Comment by aleene** [comment]
I hate splash screens.

**Comment by aleene** [comment]
I should add the off thing somewhere though.

**Comment by aleene** [comment]
Not sure what you mean with a full screen history. Idea 2 is now how the app starts.

Remember that I use the app only on the iPad, so I am a bit biased. I never actually use it on an iPhone. I only test in iPhone mode to see whether it works. I mainly use the iPad app to check and edit products. For checking a products in shops I would design something different, with coninuous scan and warnings. But without all the frills I added here. Maybe a shop tab would be a good idea. I think that is what you are looking for. Then the history tab makes sense.

**Comment by aleene** [comment]
I adapted this. The app now starts with the summary view of the last scanned product on the iPhone. The other comments are already covered by other issues.
