### ISSUE TITLE
Changing the rewind icon to a standard icon ?

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#748]
I'm not sure what the rewind icon does, and I haven't seen in any app. Clicking on it from the categories page doesn't seem to do anything.

**Comment by aleene** [comment]
In fact if you can not access that screen the app will not be working for you. I'll think of a solution.

**Comment by teolemon** [comment]
Ah ok. Also perhaps changing the icon to something like this: https://icones8.fr/icon/6904/pass%C3%A9

I didn't know it was for the history.

**Comment by aleene** [comment]
I surely will change the icon to <, which is standard on IOS. I think at the time I could not find it and forgot later.

Also I will stay in the history view, which is also intended as a summary view. It also shows warnings if the product contains allergens you specified. And it has the nutriscore and nova. I might upgrade the other elements as well. I think this will answer already several suggestions you had.

On the iPad I force the the identification view to be shown next to the summary view. On the iPhone this means that the summary view moves away. See how I can prevent that.

**Comment by aleene** [comment]
I replaced the icon with the one that is normally there. It is a stopgap, as it should have worked out of the box. Still need to investigate further.
