### ISSUE TITLE
Nutritional score tab

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#749]
- "Nutritional score" to "Nutrition Scores"
- Adding the Nutri-Score and Nova on top of the tab, above the detailed calculations
- Adding buttons linking to the webpages of the methodology: https://world-*.openfoodfacts.org/nova / https://world-*.openfoodfacts.org/nutriscore

**Comment by aleene** [comment]
Nutrional score changed
I'll add the NS and Nova in the first line and the buttons

I'll also like to add a detailed explanation why this product trigged a specific Nova score.

**Comment by aleene** [comment]
Added a line at the top. Formatting is not yet great.

**Comment by aleene** [comment]
I'll add the links to OFF for the moments, but I want a more extensive hep support.

**Comment by aleene** [comment]
The tab has been extended.
