### ISSUE TITLE
Add a text to explain what "Product defined" vs "User defined" is in settings

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#753]
Add a text to explain what "Product defined" vs "User defined" is in settings.

**Comment by aleene** [comment]
Yes that is very unclear. In fact if I look at it I do not remember what it is for.

**Comment by aleene** [comment]
I think I need to add titles to each field, as others are not intuitive as well.

**Comment by aleene** [comment]
I added titles, which explain things a bit better.
