### ISSUE TITLE
When switching units in view mode, values are truncated in the value field

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#758]
When switching units in view mode, values are truncated in the value field.
Consider putting the units in black, and removing the value field around the value.
- It will help solve the truncated value issue
- It won't create false user expectations as to editability of the value

**Comment by aleene** [comment]
How did you switch units?

**Comment by aleene** [comment]
Yes the values are calculated, so I need to round them.

Not sure why the units are in grey. Can indeed remove the squares around the values.
