### ISSUE TITLE
Separate "To be completed" and "Complete" in Community effort

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#762]
Break down the "To be completed" and "Complete" statuses into 2 sections in the Community effort, so that it's faster to see what's left to do. 
Remove the checkbox, remove completed and to be completed, and format as lists that strictly follow the order of Open Food Facts web.

Completed
Categories, Expiration date, Brands, Quantity, Nutrition Facts, Ingredients, Photo Upload, Photo Selection…

To be completed
Packaging, XXX, YYY,…

**Comment by aleene** [comment]
I can do that. I like the colour coding, as it attracts my eye right away. I use it often to see what is missing.
I did not apply any ordering yet.

PS if you tap on the missing data you will move to the correspong page for editing.

**Comment by aleene** [comment]
See also #750.
