### ISSUE TITLE
Use the language autosuggest API for the Search Query builder

### ISSUE THREAD

**Issue by teolemon** [aleene/FoodViewer#769]
https://world.openfoodfacts.org/cgi/suggest.pl?lc=fr&tagtype=languages&string=f

**Comment by aleene** [comment]
How should I use that? You mean the suggestions? I need/want to do that for any taxonomy based field. There is an issue for that.

**Comment by aleene** [comment]
I do not need the api. The langage taxonomy is incorporated in the app. I got the filter working. Unfortunately it seems I can no longer use the opOver, due to space constraints: the filter-field is clipped and no longer accesible. I need to find another solution.

**Comment by aleene** [comment]
I can use a form sheet, which partially hides the view on iPads. Then when the keyboard is shown, intercept the height of the keyboard and adjust the vertical spacing between textField and bottom.

**Comment by aleene** [comment]
It is easier to keep a fixed distance between objects and a fixed size. Otherwise the objects are jumping around when the keyboard appears.

**Comment by aleene** [comment]
I can use a form sheet, which partially hides the view on iPads. Then when the keyboard is shown, intercept the height of the keyboard and adjust the vertical spacing between textField and bottom.

**Comment by aleene** [comment]
Also needed is a cancel button (for the iPhone) and a help text.

**Comment by aleene** [comment]
Turns out I have to explicitly set the background colour of the form sheet view.

**Comment by aleene** [comment]
The code for selecting a language is repeated multiple times. Good moment to clean up the code.

**Comment by aleene** [comment]
Now that I am doing this, I can add it also to the nutrients selector.
